GET http://localhost:4004/odata/v4/trippin/People?$expand=trips&$filter=trips/any(trip:trip/budget%20ge%202000)

###
GET http://localhost:4004/odata/v4/trippin/People?$expand=trips&$filter=trips/all(trip:trip/budget%20lt%202000)